name: Playwright Automation Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24 
          cache: 'npm'
          cache-dependency-path: automation/package-lock.json

      - name: Install dependencies
        run: cd automation && npm install

      - name: Install Playwright Browsers
        run: cd automation && npx playwright install --with-deps

      - name: Run Playwright tests
        run: cd automation && npx playwright test || true

      - name: Generate API Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: api-tests/rest_assured_playwright/reports/allure-results
          gh_pages: gh-pages
          allure_report: allure-report/api
          subfolder: api

      - name: Generate Automation Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: automation/reports/allure-results
          gh_pages: gh-pages
          allure_report: allure-report/automation
          subfolder: automation

      - name: Generate Web Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: web-test/reports/allure-results
          gh_pages: gh-pages
          allure_report: allure-report/web
          subfolder: web

      - name: Copy Performance HTML to Deploy folder
        if: always()
        run: |
          mkdir -p allure-history/performance
          # summary.html dosyasını belirttiğin yoldan alıp hedef klasöre index.html olarak kopyalar
          cp performance/results/summary.html allure-history/performance/index.html 2>/dev/null || true

      - name: Deploy all reports to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history