name: Full-Stack QA Pipeline
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  web-tests:
    name: Web UI & Accessibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 24, cache: 'npm' }
      
      - name: Install & Run Web Tests
        run: |
          cd web-test
          npm install
          npx wdio run wdio.conf.ts
      
      - name: Upload Web Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-test-results
          path: web-test/reports/

  api-tests:
    name: API Lifecycle Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 24, cache: 'npm' }
      
      - name: Install & Run API Tests
        run: |
          cd api-tests/rest_assured_playwright
          npm install
          npx playwright install --with-deps
          npx playwright test
      
      - name: Upload API Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: api-tests/rest_assured_playwright/test-results/

  performance-tests:
    name: Performance Benchmarking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz -L | tar xvz
          sudo cp k6-v0.49.0-linux-amd64/k6 /usr/local/bin/
      
      - name: Run k6
        run: k6 run performance/scripts/main_test.js